### PR TITLE
feat: Add supporting for "go to line"

### PR DESCRIPTION
**Pull request by Moyf**
Hello! I have just added a new feature: "Open in VS Code and Go to the Line"!

Here are the details, I introduced 2 parameters: `{{line}}` and `{{ch}}`

As a result, if we set the tepmlate like this:
`code -g "{{vaultpath}}" "{{vaultpath}}/{{filepath}}:{{line}}:{{ch}}"`
we can directly jump into the specified line!

(VS Code's doc: https://code.visualstudio.com/docs/editor/command-line )

---

Some things you may pay attention to:
[1] I can't compile with `import * as internal from "obsidian-typings";` so I changed it to `external`, don't know would it affect anything.
image

Do you have any clues? 🤔

[2] I added a new GOTO_LINE_SETTING but I don't want to change the DEFAULT_SETTING, then I have no idea how to deal with it ... you can delete it LOL

image

### CODE REVIEW

**Comment by Moyf** [comment]
(Ooops I forgot to update the `manifest.json` )

**Comment by Moyf** [comment]
> Hey! Thanks for the feature! I'll take a look at it sometime next week. As for the manifest file, you don't need to update it. I suspected the obsidian-typings would cause some issues in the future, but it hasn't for me so far. What is your OS, Node, and npm version?

Here is my sys info:
- system: Windows 11
- npm: '10.7.0',
- node: '20.14.0',

**Comment by NomarCub** [comment]
Hi!
Everything looks good, I made some finishing touches. Could you please try if this latest version also works on your end, and the obsidian-typings import is OK too?

**Comment by Moyf** [comment]
> Hi! Everything looks good, I made some finishing touches. Could you please try if this latest version also works on your end, and the obsidian-typings import is OK too?

Just tested, the build has no problem and the function also works well  👍🏻

**Comment by NomarCub** [comment]
I just made a release with this here: https://github.com/NomarCub/obsidian-open-vscode/releases/tag/1.2.3.
Thank you for your contribution!

**Pull request merged**
