### PR TITLE
Add "Open with VS Code" option to file/folder context menu

### PR DESCRIPTION
**Pull request by quinn-p-mchugh**
This pull request is to satisfy feature request #14 (Add "Open in VS Code" to folder context menu).

## New Behavior
- When the user right-clicks a file or folder in the Obsidian file tree, a new option will be available in the context menu titled "Open with VS Code".
- Clicking this option will open the selected file/folder in VS Code, based on the CLI command they specified in their plugin settings (`Template for executing the "code" command`)
- Opening a file/folder in VS Code using this context menu simply overrides the `{{filepath}}` and `{{folderpath}}` variables used in the above setting with the path of the selected file/folder.

## Code Changes
- Added a function called `fileMenuHandler` to add the new context menu item when the user right-clicks a file/folder.
- Clicking this menu item will execute the `openVSCode` function with a new input parameter called `fileContextMenuPath` (the path of the file/folder that was right-clicked). 
- To achieve the desired functionality, I added an if statement to the `openVSCode` function to set the `filePath` and `folderPath` variables to the `fileContextMenuPath` variable instead of the path/folder of the currently open file.

## Future Work
- Since this change simply modifies the underlying behavior of the `openVSCode` function and relies on the same CLI command (`Template for executing the "code" command`) used by the existing "VSCode" command button, this update might result in some confusion for users looking to achieve different behavior when opening VS Code using the "VSCode" command button v.s. the file/folder context menu item.
- To address this, it may be beneficial to split the `Template for executing the `code` setting into two: one that is evoked when clicking the VS Code command button and the other that is evoked when clicking the file/folder context menu item.

### CODE REVIEW

**Comment by NomarCub** [comment]
Hey!
I did some modifications to your code and a bunch of maintenance. Would you please run this new version to see if it works the same on your and, and also take a look at the changes as both a user of the plugin and a developer?

**Comment by NomarCub** [comment]
@quinn-p-mchugh I'll merge this in a week, with some modification to your code and a logo change. If you have anything you want to change you have until then, or you can do it in a new PR later.

**Comment by quinn-p-mchugh** [comment]
@NomarCub 
Thanks for your patience here. I just tested the changes in my Obsidian Vault and everything works great. Please feel free to merge when you get the chance.

Also, thanks for refactoring and fixing the menu item icon. Adding a file input parameter that defaults to the active file makes the code much cleaner.

**Comment by NomarCub** [comment]
Just made a release with this in https://github.com/NomarCub/obsidian-open-vscode/releases/tag/1.3.0, thank you for your contribution!

**Comment by quinn-p-mchugh** [comment]
@NomarCub 
Wonderful! Thank you for enhancing and merging. 

Looking forward to taking advantage of this small but handy feature.

**Pull request merged**
